%% CREATE FIGURE WINDOW
function coupled11LearnGUI
fh = figure;
set(fh,'Visible','off','Toolbar','figure','Color',[.8 .8 .8],...
  'Position',[100 100 1000 600]);
initialRun
movegui(fh,'center')
set(fh,'Visible','on')

%%INITIAL RUN
function initialRun
%% Delete previous data if exist
if exist([pwd filesep 'coupled11LearnGUIdata.mat'])
  delete([pwd filesep 'coupled11LearnGUIdata.mat'])
end

%% Create title and equation
axes('Units','normalized','Position',[.025 .88 .5 .1])
axis off
text('String','Two Oscillators Connected by Plastic Coupling',...
  'Position',[0 1],'Units','normalized',...
  'HorizontalAlignment','left','VerticalAlignment','top',...
	'FontSize',13,'FontWeight','bold')
text('Interpreter','latex',...
	'String',{['$$\frac{dz_1}{dt} = z_1\left(\alpha +' ...
  '\textrm{i}\omega_1 + (\beta_1+\textrm{i}\delta_1) |z_1|^2 +' ...
  '\frac{\epsilon(\beta_2+\textrm{i}\delta_2)|z_1|^4}' ...
  '{1-\epsilon |z_1|^2}\right) + c_{12}z_2$$'],...
  ['$$\frac{dc_{12}}{dt} = c_{12}\left(\lambda + \mu_1|c_{12}|^2 +' ...
  '\frac{\epsilon_c\mu_2|c_{12}|^4}' ...
  '{1-\epsilon_c|c_{12}|^2}\right) + \kappa z_1\bar{z_2}$$']},...
	'Position',[.02 .45],'Units','normalized',...
  'HorizontalAlignment','left','VerticalAlignment','top',...
	'FontSize',11)

%% Create Full Equations & Legend button
handles.legendButton = uicontrol('Parent',gcf,'Style','pushbutton',...
  'String','<html>Full Equations<br>and Legend','FontSize',10,...
  'Units','normalized','Position',[.44 .92 .1 .07]);

%% Make text boxes for parameter input
hp1 = uipanel('Title','Parameters/Initial Values','FontSize',11,...
  'FontName','Helvetica','BackgroundColor',[.8 .8 .8],...
  'Position',[.025 .46 .5 .33]);
nc = 6; % # of columns
rb = 6; % ratio of box length relative to (half) space
wb = 1/nc*rb/(rb+2); % normalized width of boxes
ws = 1/(nc*(rb+2)); % normalized width of (half) space
wu = 1/nc; % normalized width of unit (box + space)
nr = 4; % # of rows
hb = 1/nr*.5; % normalized height of boxes
hs = 1/nr*.1; % normalized height of space below boxes
hu = 1/nr; % normalized height of unit
handles.alpha = uicontrol('Parent',hp1,'Style','edit','String','1',...
  'FontSize',11,'Units','normalized','Position',[ws hs+hu*3 wb hb]);
handles.beta1 = uicontrol('Parent',hp1,'Style','edit','String','-5',...
  'FontSize',11,'Units','normalized','Position',[ws+wu hs+hu*3 wb hb]);
handles.beta2 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*2 hs+hu*3 wb hb]);
handles.delta1 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*3 hs+hu*3 wb hb]);
handles.delta2 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*4 hs+hu*3 wb hb]);
handles.epsilon = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*5 hs+hu*3 wb hb]);

handles.lambda = uicontrol('Parent',hp1,'Style','edit','String','1',...
  'FontSize',11,'Units','normalized','Position',[ws hs+hu*2 wb hb]);
handles.mu1 = uicontrol('Parent',hp1,'Style','edit','String','-10',...
  'FontSize',11,'Units','normalized','Position',[ws+wu hs+hu*2 wb hb]);
handles.mu2 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*2 hs+hu*2 wb hb]);
handles.kappa = uicontrol('Parent',hp1,'Style','edit','String','1',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*3 hs+hu*2 wb hb]);
handles.epsilonc = uicontrol('Parent',hp1,'Style','edit','String','1',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*4 hs+hu*2 wb hb]);
handles.duration = uicontrol('Parent',hp1,'Style','edit','String','30',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*5 hs+hu*2 wb hb]);

handles.fz1 = uicontrol('Parent',hp1,'Style','edit','String','1.1',...
  'FontSize',11,'Units','normalized','Position',[ws hs+hu wb hb]);
handles.fz2= uicontrol('Parent',hp1,'Style','edit','String','1',...
  'FontSize',11,'Units','normalized','Position',[ws+wu hs+hu wb hb]);
handles.r10 = uicontrol('Parent',hp1,'Style','edit','String','.1',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*2 hs+hu wb hb]);
handles.phi10 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*3 hs+hu wb hb]);
handles.r20 = uicontrol('Parent',hp1,'Style','edit','String','.2',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*4 hs+hu wb hb]);
handles.phi20 = uicontrol('Parent',hp1,'Style','edit','String','.3',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*5 hs+hu wb hb]);

handles.A120 = uicontrol('Parent',hp1,'Style','edit','String','.1',...
  'FontSize',11,'Units','normalized','Position',[ws hs wb hb]);
handles.theta120 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu hs wb hb]);
handles.A210 = uicontrol('Parent',hp1,'Style','edit','String','.2',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*2 hs wb hb]);
handles.theta210 = uicontrol('Parent',hp1,'Style','edit','String','.4',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*3 hs wb hb]);


%% Labels for text boxes
axes('Units','normalized','Position',get(hp1,'Position'))
axis off
lfs = 14; % Label font size
pos1 = .83;
text(wu/2,pos1,'$$\alpha$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*3/2,pos1,'$$\beta_1$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*5/2,pos1,'$$\beta_2$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*7/2,pos1,'$$\delta_1$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*9/2,pos1,'$$\delta_2$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*11/2,pos1,'$$\epsilon$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)

pos2 = .61;
text(wu/2,pos2,'$$\lambda$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*3/2,pos2,'$$\mu_1$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*5/2,pos2,'$$\mu_2$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*7/2,pos2,'$$\kappa$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*9/2,pos2,'$$\epsilon_c$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*11/2,pos2,'Duration','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs-1)

pos3 = .39;
text(wu/2,pos3,'$$\omega_1/2\pi$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalize','FontSize',lfs)
text(wu*3/2,pos3,'$$\omega_2/2\pi$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*5/2,pos3,'$$r_{10}$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*7/2,pos3,'$$\phi_{10}/2\pi$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*9/2,pos3,'$$r_{20}$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*11/2,pos3,'$$\phi_{20}/2\pi$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)

pos4 = .17;
text(wu/2,pos4,'$$A_{120}$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*3/2,pos4,'$$\theta_{120}/2\pi$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalize','FontSize',lfs)
text(wu*5/2,pos4,'$$A_{210}$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*7/2,pos4,'$$\theta_{210}/2\pi$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalize','FontSize',lfs)

%% Create Run button
handles.runButton = uicontrol('Parent',hp1,'Style','pushbutton',...
  'String','Run','FontSize',11,'Units','normalized',...
  'Position',[wu*4+ws hs wu*2-ws*2 hb*1.5]);

%% Create Time Plot panel
hp2 = uipanel('Title','Choose Time Plot','FontSize',11,...
  'BackgroundColor',[.8 .8 .8],'Position',[.025 .015 .95 .44]);
handles.plotType = uicontrol('Parent',hp2,'Style','popup',...
  'String',['Real part|Imaginary part|Amplitude|' ...
  'Relative phase 1|Relative phase 2|Instantaneous frequency'],...
  'FontSize',11,'Units','normalized','Position',[.015 .88 .2 .1]);
handles.ax1 = axes('Position',[.1 .08 .85 .25],'Units','normalized',...
  'XTick',[],'YTick',[],'box','on');
text(.5,.5,'Run simulation','FontSize',15,...
  'HorizontalAlignment','center','VerticalAlignment','middle',...
  'Units','normalized')

%% Create Phase Portrait panel
uipanel('Title','Phase Portrait & Vector Field','FontSize',11,...
  'BackgroundColor',[.8 .8 .8],'Position',[.55 .45 .425 .54]);
handles.ax2 = axes('Position',[.66 .46 .3 .5],'Units','normalized',...
  'XTick',[],'YTick',[],'box','on');
polar2(NaN,NaN,[0 1]);

%% Define callback functions
set(handles.runButton,'Callback',{@integrate,handles})
set(handles.plotType,'Callback',{@plotAxes1,handles})
set(handles.legendButton,'Callback',@showLegend)

%% INTEGRATE
function integrate(~,~,handles)
% Get parameters
p.a = str2double(get(handles.alpha,'String'));
p.b1 = str2double(get(handles.beta1,'String'));
p.b2 = str2double(get(handles.beta2,'String'));
p.d1 = str2double(get(handles.delta1,'String'));
p.d2 = str2double(get(handles.delta2,'String'));
p.e = str2double(get(handles.epsilon,'String'));
p.fz1 = str2double(get(handles.fz1,'String'));
p.fz2 = str2double(get(handles.fz2,'String'));

p.l = str2double(get(handles.lambda,'String'));
p.m1 = str2double(get(handles.mu1,'String'));
p.m2 = str2double(get(handles.mu2,'String'));
p.ka = str2double(get(handles.kappa,'String'));
p.ec = str2double(get(handles.epsilonc,'String'));
endtime = str2double(get(handles.duration,'String'));

fs = ceil(max([p.fz1; p.fz2]))*20;
t = (0:1/fs:endtime*1)';
z10 = str2double(get(handles.r10,'String')) ...
  *exp(1i*2*pi*str2double(get(handles.phi10,'String')));
z20 = str2double(get(handles.r20,'String')) ...
  *exp(1i*2*pi*str2double(get(handles.phi20,'String')));
c120 = str2double(get(handles.A120,'String')) ...
  *exp(1i*2*pi*str2double(get(handles.theta120,'String')));
c210 = str2double(get(handles.A210,'String')) ...
  *exp(1i*2*pi*str2double(get(handles.theta210,'String')));

%% Integrate
ZC = ode4(@(t,zc)zcdot(t,zc,p),t,[z10; z20; c120; c210]);
Z1 = ZC(:,1);
Z2 = ZC(:,2);
C12 = ZC(:,3);
C21 = ZC(:,4);

save coupled11LearnGUIdata Z1 Z2 C12 C21 t p fs
plotAxes1([],[],handles)
plotAxes2([],[],handles)

%% DRAW TIME PLOT
function plotAxes1(~,~,handles)
axes(handles.ax1)
cla
if exist([pwd filesep 'coupled11LearnGUIdata.mat']) % if simulation data exist
  load coupled11LearnGUIdata
  val = get(handles.plotType,'Value');
  if val == 1 % real parts
    plot(t,real(Z1),t,real(Z2),t,real(C12),t,real(C21))
    ylabel('')
    ymax = max(max(abs([Z1 Z2 C12 C21])));
    set(gca,'XLim',[min(t) max(t)],'YLim',[-1 1]*ymax*1.1)
    hl = legend('Re({\itz}_1)','Re({\itz}_2)','Re({\itc}_{12})',...
      'Re({\itc}_{21})','Location','NorthEast','Orientation','horizontal');
    lpos = get(hl,'Position');
    lpos(2) = .35;
    set(hl,'Position',lpos)
  elseif val == 2 % imaginary parts
    plot(t,imag(Z1),t,imag(Z2),t,imag(C12),t,imag(C21))
    ylabel('')
    ymax = max(max(abs([Z1 Z2 C12 C21])));
    set(gca,'XLim',[min(t) max(t)],'YLim',[-1 1]*ymax*1.1)
    hl = legend('Im({\itz}_1)','Im({\itz}_2)','Im({\itc}_{12})',...
      'Im({\itc}_{21})','Location','NorthEast','Orientation','horizontal');
    lpos = get(hl,'Position');
    lpos(2) = .35;
    set(hl,'Position',lpos)
  elseif val == 3 % amplitude
    plot(t,abs(Z1),t,abs(Z2),t,abs(C12),t,abs(C21))
    set(gca,'XLim',[min(t) max(t)])
    hl = legend('{\itr}_1','{\itr}_2','{\itA}_{12}','{\itA}_{21}',...
      'Location','NorthEast','Orientation','horizontal');
    lpos = get(hl,'Position');
    lpos(2) = .35;
    set(hl,'Position',lpos)
  elseif val == 4 % relative phase (psi)
    hrp = plot(t,angle(C12.*Z2.*conj(Z1)),t,angle(C21.*Z1.*conj(Z2)));
    set(hrp,'LineStyle','none','Marker','.','MarkerSize',5)
    set(gca,'XLim',[min(t) max(t)])
    set(gca,'YLim',pi*[-1 1],'YTick',[-pi,-pi/2,0,pi/2,pi],...
      'YTickLabel',{'-pi';'-pi/2';'0';'pi/2';'pi'})
    ylabel('{\it\psi_{ij}}')
    hl = legend('{\it\psi}_{12}','{\it\psi}_{21}',...
      'Location','NorthEast','Orientation','horizontal');
    lpos = get(hl,'Position');
    lpos(2) = .35;
    set(hl,'Position',lpos)
  elseif val == 5 % relative phase (phi_i - phi_j, theta_{ij})
    hrp = plot(t,angle(Z1.*conj(Z2)),t,angle(C12),...
      t,angle(Z2.*conj(Z1)),t,angle(C21));
    set(hrp,'LineStyle','none','Marker','.','MarkerSize',5)
    set(gca,'XLim',[min(t) max(t)])
    set(gca,'YLim',pi*[-1 1],'YTick',[-pi,-pi/2,0,pi/2,pi],...
      'YTickLabel',{'-pi';'-pi/2';'0';'pi/2';'pi'})
    hl = legend('{\it\phi}_1 - {\it\phi}_2','{\it\theta}_{12}',...
      '{\it\phi}_2 - {\it\phi}_1','{\it\theta}_{21}',...
      'Location','NorthEast','Orientation','horizontal');
    lpos = get(hl,'Position');
    lpos(2) = .35;
    set(hl,'Position',lpos)
  elseif val == 6 % instantaneous frequency
    instFreqZ1 = angle(Z1(2:end,:).*conj(Z1(1:end-1,:)))*fs/(2*pi);
    instFreqZ2 = angle(Z2(2:end,:).*conj(Z2(1:end-1,:)))*fs/(2*pi);
    instFreqC12 = angle(C12(2:end,:).*conj(C12(1:end-1,:)))*fs/(2*pi);
    instFreqC21 = angle(C21(2:end,:).*conj(C21(1:end-1,:)))*fs/(2*pi);
    plot(t(1:end-1),instFreqZ1,t(1:end-1),instFreqZ2,...
      t(1:end-1),instFreqC12,t(1:end-1),instFreqC21)
    ylabel('Instantaneous frequency')
    set(gca,'XLim',[t(2) t(end)])
    hl = legend('{\itz}_1','{\itz}_2','{\itc}_{12}','{\itc}_{21}',...
      'Location','NorthEast','Orientation','horizontal');
    lpos = get(hl,'Position');
    lpos(2) = .35;
    set(hl,'Position',lpos)
  end
  xlabel('Time')
  grid on
else
  text(.5,.5,'Run simulation first','FontSize',15,...
    'HorizontalAlignment','center','VerticalAlignment','middle',...
    'Units','normalized')
end

%% DRAW PHASE PORTRAIT
function plotAxes2(~,~,handles)
axes(handles.ax2)
cla
load coupled11LearnGUIdata

if p.e
  rmax = 1/sqrt(p.e)*.99;
else
  rmax = max(max(abs([Z1 Z2])))*1.2;
end

polar2(NaN,NaN,[0 rmax],'-');
hold on

%% Draw trajectory
hz1 = polar2(angle(C12.*Z2.*conj(Z1)),abs(Z1),[0 rmax],'b-');
set(hz1,'LineWidth',2)
hz2 = polar2(angle(C21.*Z1.*conj(Z2)),abs(Z2),[0 rmax],'m-');
set(hz2,'LineWidth',2)
hz3 = polar2(angle(C12(1).*Z2(1).*conj(Z1(1))),abs(Z1(1)),[0 rmax],'ko');
set(hz3,'MarkerSize',5)
hz4 = polar2(angle(C21(1).*Z1(1).*conj(Z2(1))),abs(Z2(1)),[0 rmax],'ko');
set(hz4,'MarkerSize',5)
hold off
hl = legend([hz1,hz2,hz3],'{\itr}_1{\ite}^{i{\it\psi}_{12}}',...
  '{\itr}_2{\ite}^{i{\it\psi}_{21}}','Initial pts','Location','NorthWest');
lpos = get(hl,'Position');
lpos(1) = .555;
lpos(2) = .8;
set(hl,'Position',lpos)

%% SHOW LEGEND
function showLegend(~,~)
hf = figure;
fpos = get(hf,'Position');

set(hf,'Position',[fpos(1) fpos(2) 600 300])
axes('Units','normalized','Position',[0 0 1 1]);
axis off
text('Interpreter','latex',...
	'String',{['$$\frac{dz_1}{dt} = z_1\left(\alpha +' ...
  '\textrm{i}\omega_1 + (\beta_1+\textrm{i}\delta_1) |z_1|^2 +' ...
  '\frac{\epsilon(\beta_2+\textrm{i}\delta_2)|z_1|^4}' ...
  '{1-\epsilon |z_1|^2}\right) + c_{12}z_2$$'],...
  ['$$\frac{dz_2}{dt} = z_2\left(\alpha +' ...
  '\textrm{i}\omega_2 + (\beta_1+\textrm{i}\delta_1) |z_2|^2 +' ...
  '\frac{\epsilon(\beta_2+\textrm{i}\delta_2)|z_2|^4}' ...
  '{1-\epsilon |z_2|^2}\right) + c_{21}z_1$$'],...
  ['$$\frac{dc_{12}}{dt} = c_{12}\left(\lambda + \mu_1|c_{12}|^2 +' ...
  '\frac{\epsilon_c\mu_2|c_{12}|^4}' ...
  '{1-\epsilon_c|c_{12}|^2}\right) + \kappa z_1\bar{z_2}$$'],...
  ['$$\frac{dc_{21}}{dt} = c_{21}\left(\lambda + \mu_1|c_{21}|^2 +' ...
  '\frac{\epsilon_c\mu_2|c_{21}|^4}' ...
  '{1-\epsilon_c|c_{21}|^2}\right) + \kappa z_2\bar{z_1}$$'],...
  '$$\quad$$','$$\quad$$',...
  ['$$z_i = r_ie^{\textrm{i}\phi_i},' ...
  'c_{ij} = A_{ij}e^{\textrm{i}\theta_{ij}}$$, and ' ...
  '$$\psi_{ij}=\theta_{ij}-\phi_i+\phi_j$$']},...
	'Position',[.05 .9],'Units','normalized',...
  'HorizontalAlignment','left','VerticalAlignment','top',...
	'FontSize',15)

%% DIFFERENTIAL EQUATION
function dzcdt = zcdot(t,zc,p)
z1 = zc(1);
z2 = zc(2);
c12 = zc(3);
c21 = zc(4);

dz1dt = z1.*(p.a + 1i*2*pi*p.fz1 + (p.b1+1i*p.d1)*abs(z1).^2 + ...
  p.e*(p.b2+1i*p.d2)*abs(z1).^4./(1-p.e*abs(z1).^2)) + c12*z2;
dz2dt = z2.*(p.a + 1i*2*pi*p.fz2 + (p.b1+1i*p.d1)*abs(z2).^2 + ...
  p.e*(p.b2+1i*p.d2)*abs(z2).^4./(1-p.e*abs(z2).^2)) + c21*z1;
dc12dt = c12.*(p.l + p.m1*abs(c12).^2 + ...
    p.ec*p.m2*abs(c12).^4./(1-p.ec*abs(c12).^2)) + p.ka*z1*conj(z2);
dc21dt = c21.*(p.l + p.m1*abs(c21).^2 + ...
    p.ec*p.m2*abs(c21).^4./(1-p.ec*abs(c21).^2)) + p.ka*z2*conj(z1);
dzcdt = [dz1dt; dz2dt; dc12dt; dc21dt];
