%% CREATE FIGURE WINDOW
function driven11LearnGUI
hf = figure;
set(hf,'Visible','off','Toolbar','figure','Color',[.8 .8 .8],...
  'Position',[100 100 1000 600]);
initialRun
movegui(hf,'center')
set(hf,'Visible','on')

%% INITIAL RUN
function initialRun
hf = gcf;
handles.hf = hf;

%% Create title and equation
axes('Parent',hf,'Units','normalized','Position',[.025 .88 .5 .1]);
axis off
text('String',['Oscillator Driven by a Sinusoid ' ...
  'via Plastic Coupling'],...
  'Position',[0 1],'Units','normalized',...
  'HorizontalAlignment','left','VerticalAlignment','top',...
  'FontSize',13,'FontWeight','bold')
text('Interpreter','latex',...
  'String',{['$$\frac{dz}{dt} = z\left(\alpha + \textrm{i}\omega +' ...
  '(\beta_1+\textrm{i}\delta_1) |z|^2 +' ...
  '\frac{\epsilon(\beta_2+\textrm{i}\delta_2)|z|^4}' ...
  '{1-\epsilon |z|^2}\right) + cx$$'],...
  ['$$\frac{dc}{dt} = c\left(\lambda + \mu_1|c|^2 +' ...
  '\frac{\epsilon_c\mu_2|c|^4}' ...
  '{1-\epsilon_c|c|^2}\right) + \kappa z\bar{x}$$']},...
  'Position',[.02 .45],'Units','normalized',...
  'HorizontalAlignment','left','VerticalAlignment','top',...
  'FontSize',11)

%% Create Legend button
handles.legendButton = uicontrol('Parent',hf,'Style','pushbutton',...
  'String','Legend','FontSize',10,'Units','normalized',...
  'Position',[.455 .88 .07 .05]);

%% Make text boxes for parameter input
hp1 = uipanel('Parent',hf,'Title','Parameters & Initial Values',...
  'FontSize',11,'BackgroundColor',[.8 .8 .8],'Units','normalized',...
  'Position',[.025 .46 .5 .33]);
nc = 6; % # of columns
rb = 6; % ratio of box length relative to (half) space
wb = 1/nc*rb/(rb+2); % normalized width of boxes
ws = 1/(nc*(rb+2)); % normalized width of (half) space
wu = 1/nc; % normalized width of unit (box + space)
nr = 4; % # of rows
hb = 1/nr*.5; % normalized height of boxes
hs = 1/nr*.1; % normalized height of space below boxes
hu = 1/nr; % normalized height of unit
handles.alpha = uicontrol('Parent',hp1,'Style','edit','String','1',...
  'FontSize',11,'Units','normalized','Position',[ws hs+hu*3 wb hb]);
handles.beta1 = uicontrol('Parent',hp1,'Style','edit','String','-10',...
  'FontSize',11,'Units','normalized','Position',[ws+wu hs+hu*3 wb hb]);
handles.beta2 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*2 hs+hu*3 wb hb]);
handles.delta1 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*3 hs+hu*3 wb hb]);
handles.delta2 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*4 hs+hu*3 wb hb]);
handles.epsilon = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*5 hs+hu*3 wb hb]);

handles.lambda = uicontrol('Parent',hp1,'Style','edit','String','1',...
  'FontSize',11,'Units','normalized','Position',[ws hs+hu*2 wb hb]);
handles.mu1 = uicontrol('Parent',hp1,'Style','edit','String','-10',...
  'FontSize',11,'Units','normalized','Position',[ws+wu hs+hu*2 wb hb]);
handles.mu2 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*2 hs+hu*2 wb hb]);
handles.kappa = uicontrol('Parent',hp1,'Style','edit','String','1',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*3 hs+hu*2 wb hb]);
handles.epsilonc = uicontrol('Parent',hp1,'Style','edit','String','1',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*4 hs+hu*2 wb hb]);
handles.duration = uicontrol('Parent',hp1,'Style','edit','String','10',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*5 hs+hu*2 wb hb]);

handles.fz = uicontrol('Parent',hp1,'Style','edit','String','1.1',...
  'FontSize',11,'Units','normalized','Position',[ws hs+hu wb hb]);
handles.f0 = uicontrol('Parent',hp1,'Style','edit','String','1',...
  'FontSize',11,'Units','normalized','Position',[ws+wu hs+hu wb hb]);
handles.F = uicontrol('Parent',hp1,'Style','edit','String','1',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*2 hs+hu wb hb]);
handles.vartheta0 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*3 hs+hu wb hb]);


handles.r0 = uicontrol('Parent',hp1,'Style','edit','String','.1',...
  'FontSize',11,'Units','normalized','Position',[ws hs wb hb]);
handles.phi0 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu hs wb hb]);
handles.A0 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*2 hs wb hb]);
handles.theta0 = uicontrol('Parent',hp1,'Style','edit','String','0',...
  'FontSize',11,'Units','normalized','Position',[ws+wu*3 hs wb hb]);


%% Labels for text boxes
axes('Parent',hp1,'Units','normalized','Position',[0 0 1 1])
axis off
lfs = 14; % Label font size
pos1 = hu*3.7;
text(wu/2,pos1,'$$\alpha$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*3/2,pos1,'$$\beta_1$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*5/2,pos1,'$$\beta_2$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*7/2,pos1,'$$\delta_1$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*9/2,pos1,'$$\delta_2$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*11/2,pos1,'$$\epsilon$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)

pos2 = hu*2.7;
text(wu/2,pos2,'$$\lambda$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*3/2,pos2,'$$\mu_1$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*5/2,pos2,'$$\mu_2$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*7/2,pos2,'$$\kappa$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*9/2,pos2,'$$\epsilon_c$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*11/2,pos2,'Duration','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs-1)

pos3 = hu*1.7;
text(wu/2,pos3,'$$\omega/2\pi$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalize','FontSize',lfs)
text(wu*3/2,pos3,'$$\omega_0/2\pi$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*5/2,pos3,'$$F$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*7/2,pos3,'$$\vartheta_0/2\pi$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)

pos4 = hu*.7;
text(wu/2,pos4,'$$r_0$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*3/2,pos4,'$$\phi_0/2\pi$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalize','FontSize',lfs)
text(wu*5/2,pos4,'$$A_0$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalized','FontSize',lfs)
text(wu*7/2,pos4,'$$\theta_0/2\pi$$','Interpreter','Latex',...
  'HorizontalAlignment','center','VerticalAlignment','baseline',...
  'Units','normalize','FontSize',lfs)

%% Create Run button
handles.runButton = uicontrol('Parent',hp1,'Style','pushbutton',...
  'String','Run','FontSize',11,'Units','normalized',...
  'Position',[wu*4+ws hs wu*2-ws*2 hu+hb]);

%% Create Time Plot panel
hp4 = uipanel('Parent',hf,'Title','Choose Time Plot','FontSize',11,...
  'BackgroundColor',[.8 .8 .8],'Units','normalized',...
  'Position',[.025 .015 .95 .44]);
handles.plotType = uicontrol('Parent',hp4,'Style','popup',...
  'String',['Real part|Imaginary part|Amplitude|' ...
  'Relative phase 1|Relative phase 2|Instantaneous frequency'],...
  'FontSize',11,'Units','normalized','Position',[.015 .88 .2 .1]);
handles.ax1 = axes('Parent',hp4,'Units','normalized',...
  'Position',[.075 .2 .9 .6],'XTick',[],'YTick',[],'box','on');
text(.5,.5,'Run simulation','FontSize',15,...
  'HorizontalAlignment','center','VerticalAlignment','middle',...
  'Units','normalized')

%% Create Phase Portrait panel
hp5 = uipanel('Parent',hf,'Title','Phase Portrait & Vector Field',...
  'FontSize',11,'BackgroundColor',[.8 .8 .8],'Units','normalized',...
  'Position',[.55 .45 .425 .54]);
handles.ax2 = axes('Parent',hp5,'Units','normalized',...
  'Position',[.2 0 .8 1],'XTick',[],'YTick',[],'box','on');
polar2(NaN,NaN,[0 1]);

%% Define callback functions
set(handles.runButton,'Callback',{@integrate,handles})
set(handles.plotType,'Callback',{@plotAxes1,handles})
set(handles.legendButton,'Callback',@showLegend)

%% INTEGRATE
function integrate(~,~,handles)
%% Get parameters
p.a = str2double(get(handles.alpha,'String'));
p.b1 = str2double(get(handles.beta1,'String'));
p.b2 = str2double(get(handles.beta2,'String'));
p.d1 = str2double(get(handles.delta1,'String'));
p.d2 = str2double(get(handles.delta2,'String'));
p.e = str2double(get(handles.epsilon,'String'));
p.fz = str2double(get(handles.fz,'String'));

p.l = str2double(get(handles.lambda,'String'));
p.m1 = str2double(get(handles.mu1,'String'));
p.m2 = str2double(get(handles.mu2,'String'));
p.ka = str2double(get(handles.kappa,'String'));
p.ec = str2double(get(handles.epsilonc,'String'));

s.F = str2double(get(handles.F,'String'));
s.f = str2double(get(handles.f0,'String'));
s.theta0 = str2double(get(handles.vartheta0,'String'))*2*pi;
s.endtime = str2double(get(handles.duration,'String'));

%% Integrate
fs = ceil(max([p.fz; s.f]))*20;
t = (0:1/fs:s.endtime*1)';
z0 = str2double(get(handles.r0,'String')) ...
  *exp(1i*2*pi*str2double(get(handles.phi0,'String')));
c0 = str2double(get(handles.A0,'String')) ...
  *exp(1i*2*pi*str2double(get(handles.theta0,'String')));

ZC = ode4(@(t,zc)zcdot(t,zc,p,s),t,[z0; c0]);
Z = ZC(:,1);
C = ZC(:,2);

s.x = s.F.*exp(1i*(2*pi*s.f*t+s.theta0));
M.Z = Z; M.C = C; M.t = t; M.p = p; M.s = s; M.fs = fs;
guidata(handles.hf,M)
plotAxes1([],[],handles)
plotAxes2([],[],handles)

%% DRAW TIME PLOT
function plotAxes1(~,~,handles)
axes(handles.ax1)
cla
M = guidata(handles.hf);
if ~isempty(M)
  Z = M.Z; C = M.C; t = M.t; s = M.s; fs = M.fs;
  val = get(handles.plotType,'Value');
  if val == 1 % real parts
    plot(t,real(Z),t,real(C),t,real(s.x),'--')
    ylabel('')
    ymax = max(max([abs(Z);abs(C)]),s.F);
    set(gca,'YLim',[-1 1]*ymax*1.1)
    hl = legend('Re({\itz})','Re({\itc})','Re({\itx})',...
      'Location','NorthEast','Orientation','horizontal');
  elseif val == 2 % imaginary parts
    plot(t,imag(Z),t,imag(C),t,imag(s.x),'--')
    ylabel('')
    ymax = max(max([abs(Z);abs(C)]),s.F);
    set(gca,'YLim',[-1 1]*ymax*1.1)
    hl = legend('Im({\itz})','Im({\itc})','Im({\itx})',...
      'Location','NorthEast','Orientation','horizontal');
  elseif val == 3 % amplitude
    plot(t,abs(Z),t,abs(C))
    hl = legend('{\itr}','{\itA}',...
      'Location','NorthEast','Orientation','horizontal');
  elseif val == 4 % relative phase (psi)
    hrp = plot(t,angle(C.*s.x.*conj(Z)));
    set(hrp,'LineStyle','none','Marker','.','MarkerSize',5)
    set(gca,'YLim',pi*[-1 1],'YTick',[-pi,-pi/2,0,pi/2,pi],...
      'YTickLabel',{'-pi';'-pi/2';'0';'pi/2';'pi'})
    ylabel('{\it\psi}')
  elseif val == 5 % relative phase (phi - vartheta, theta)
    hrp = plot(t,angle(Z.*conj(s.x)),t,angle(C));
    set(hrp,'LineStyle','none','Marker','.','MarkerSize',5)
    set(gca,'YLim',pi*[-1 1],'YTick',[-pi,-pi/2,0,pi/2,pi],...
      'YTickLabel',{'-pi';'-pi/2';'0';'pi/2';'pi'})
    hl = legend('{\it\phi} - {\it\vartheta}','{\it\theta}',...
      'Location','NorthEast','Orientation','horizontal');
  elseif val == 6 % instantaneous frequency
    instFreqZ = angle(Z(2:end,:).*conj(Z(1:end-1,:)))*fs/(2*pi);
    instFreqC = angle(C(2:end,:).*conj(C(1:end-1,:)))*fs/(2*pi);
    plot(t(1:end-1),instFreqZ,t(1:end-1),instFreqC,...
      t([1 end-1]),[1 1]*s.f,'--')
    ylabel('Instantaneous frequency')
    hold off
    hl = legend('{\itz}','{\itc}','{\itx}','Location','NorthEast',...
      'Orientation','horizontal');
  end
  xlabel('Time')
  set(gca,'XLim',[min(t) max(t)])
  grid on
  if exist('hl','var')
    lpos = get(hl,'Position');
    lpos(2) = .88;
    set(hl,'Position',lpos)
  end
else
  text(.5,.5,'Run simulation first','FontSize',15,...
    'HorizontalAlignment','center','VerticalAlignment','middle',...
    'Units','normalized')
end

%% DRAW PHASE PORTRAIT
function plotAxes2(~,~,handles)
axes(handles.ax2)
cla
M = guidata(handles.hf);
Z = M.Z; C = M.C; p = M.p; s = M.s;

if p.e
  rmax = 1/sqrt(p.e)*.99;
else
  rmax = max(abs(Z))*1.2;
end

polar2(NaN,NaN,[0 rmax],'-');
hold on

%% Draw trajectory
hz1 = polar2(angle(C.*s.x.*conj(Z)),abs(Z),[0 rmax],'-');
set(hz1,'LineWidth',2,'Color',lines(1))
hz2 = polar2(angle(C(1).*s.x(1).*conj(Z(1))),abs(Z(1)),[0 rmax],'ko');
set(hz2,'MarkerSize',5)
hold off
hl = legend([hz1,hz2],'{\itre}^{i{\it\psi}}','Initial point',...
  'Location','NorthWest');
lpos = get(hl,'Position');
lpos(1) = .02;
lpos(2) = .85;
set(hl,'Position',lpos)

%% SHOW LEGEND
function showLegend(~,~)
hf = figure;
fpos = get(hf,'Position');

set(hf,'Position',[fpos(1) fpos(2) 350 140])
axes('Units','normalized','Position',[0 0 1 1]);
axis off
text('Interpreter','latex','String',{'$$z = re^{\textrm{i}\phi}$$,',...
  '$$c = Ae^{\textrm{i}\theta}$$,',...
  ['$$x = Fe^{\textrm{i}\vartheta}$$ '...
  'where $$\vartheta = \omega_0t+\vartheta_0$$, and'],...
  '$$\psi=\theta-\phi+\vartheta$$'},...
  'Position',[.05 .9],'Units','normalized',...
  'HorizontalAlignment','left','VerticalAlignment','top',...
  'FontSize',15)

%% DIFFERENTIAL EQUATION
function dzcdt = zcdot(t,zc,p,s)
z = zc(1);
c = zc(2);
x = sum(s.F.*exp(1i*(2*pi*s.f*t+s.theta0)));
dzdt = z.*(p.a + 1i*2*pi*p.fz + (p.b1+1i*p.d1)*abs(z).^2 + ...
  p.e*(p.b2+1i*p.d2)*abs(z).^4./(1-p.e*abs(z).^2)) + c*x;
dcdt = c.*(p.l + p.m1*abs(c).^2 + ...
  p.ec*p.m2*abs(c).^4./(1-p.ec*abs(c).^2)) + p.ka*z*conj(x);
dzcdt = [dzdt; dcdt];
